version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./config/apache:/etc/apache2/sites-available
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=user_service
      - DB_USER=root
      - DB_PASS=rootpassword
      - JWT_SECRET=your-super-secret-jwt-key-change-this
    networks:
      - user-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_service
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - user-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - db
    networks:
      - user-network

volumes:
  db_data:

networks:
  user-network:
    driver: bridge
